### ISSUE TITLE
Some minor refactoring

### ISSUE THREAD

**Issue by kareemmahlees** [the-sabra/basic-go-api#1]
Hi omar, nice job creating such a well thoughted and structured project 👏🏻.
I took a look into the code and found some parts maybe improved a bit ( most of the them are nitpicks tbh ), there is no change in the functionality, only the structure of the code..

Here are some points I noticed:
- the `main` function is bloated, it should only contain a `run` or `serve` function the returns an error
- the [jwt struct](https://github.com/the-sabra/basic-go-api/blob/a0ea72d57aa78d6b470ac9c6aa4af48baa53c7f5/util/jwt.go#L11C6-L11C22) in `jwt.go` should contain the function declared below it as a method.
-  the handlers a lot more than _handling_ requests. checking if the user exists, hashing the password and such should go into the storage layer.

This is not by no means a criticism, I just wanted to share some of my **minute**  golang experience with you. So, in that sense I am happy to create a PR incorporating these changes 🙂

**Comment by thesabrah** [comment]
I'm sorry I'm late. Please go ahead, your edits make me learn more
